#!/bin/sh
npm run | grep -Gxq "^\W*test$"
has_npm_test=$?
if [ $has_npm_test -eq 0 ]; then
  echo "Running npm test"
  npm test
  test_passed=$?
  if [ $test_passed -ne 0 ]; then
    tput setaf 1
    echo "Test failed - push rejected"
    tput sgr0
    exit 1
  else
    echo "Test succeeded"
  fi
fi
exit 0