export BROWSER=/usr/bin/firefox
export EDITOR=/usr/bin/nvim
export REACT_DEBUGGER="pidof 'React Native Debugger' || react-native-debugger"
export Q_INSPECT_NOTIFY_EMAIL=jonasdamtoft@hotmail.com
export GEM_PATH=$HOME/.gem/ruby/2.5.0
export CHROME_BIN=/usr/bin/chromium
export PATH=$HOME/.local/bin:$GEM_PATH/bin:$PATH
export LC_ALL=en_DK.utf8
export LANG=en_DK.utf8
export ELECTRON_TRASH=trash-cli
export nvm_prefix=/usr/share/nvm
