export BROWSER=/usr/bin/firefox
export EDITOR=/usr/bin/nvim
export REACT_DEBUGGER="pidof 'React Native Debugger' || react-native-debugger"
export Q_INSPECT_NOTIFY_EMAIL=jonasdamtoft@hotmail.com
export NPM_PACKAGES=$HOME/.local
export GEM_PATH=$HOME/.gem/ruby/2.5.0
export CHROME_BIN=/usr/bin/chromium
export PATH=$NPM_PACKAGES/bin:$GEM_PATH/bin:$PATH
export LC_ALL=en_DK.utf8
export LANG=en_DK.utf8
