# -*- mode:Shell-script -*-
export ZPLUG_HOME=~/.zplug
export ZSH=~/.zsh
export ZSH_CACHE=~/.zsh_cache
export EDITOR='vi'
export VISUAL='emacs -nw'
export BROWSER='firefox'
export JAVA_HOME=/usr/lib64/jvm/java
