# -*- mode:Shell-script -*-
autoload colors
colors

# zplug
# Bootstrap
if [[ ! -d $ZPLUG_HOME ]]; then
    echo "Installing zplug..."
    if git clone https://github.com/zplug/zplug $ZPLUG_HOME; then
        echo "SUCCESS: Installed zplug into $ZPLUG_HOME"
    else
        echo "$fg[red]ERROR: Failed while installing zplug! $fg[default]"
    fi
fi

if [[ -d $ZPLUG_HOME ]]; then
    source $ZPLUG_HOME/init.zsh
fi

if [[ ! -d $ZSH ]]; then
    mkdir -p $ZSH
fi

if [[ ! -d $ZSH_CACHE ]]; then
    mkdir -p $ZSH_CACHE
fi

zplug 'zplug/zplug', hook-build:'zplug --self-manage'

# Theme
zplug "mafredri/zsh-async", defer:0
zplug "sindresorhus/pure", use:"pure.zsh", as:theme

# Plugins
zplug "$ZSH", from:local, use:"*.zsh"
zplug "oz/safe-paste"
zplug "knu/zsh-manydots-magic", use:manydots-magic

zplug 'zsh-users/zsh-autosuggestions'
zplug 'zsh-users/zsh-syntax-highlighting'
zplug 'zsh-users/zsh-history-substring-search'

# Execute
zplug check || zplug install
zplug load

# Bindings for history-substring-search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down
