# -*- mode:Shell-script -*-
autoload colors
colors

# zplug
# Bootstrap
if [[ ! -d $ZPLUG_HOME ]]; then
    echo "Installing zplug..."
    if git clone https://github.com/zplug/zplug $ZPLUG_HOME; then
        echo "SUCCESS: Installed zplug into $ZPLUG_HOME"
    else
        echo "$fg[red]ERROR: Failed while installing zplug! $fg[default]"
    fi
fi

if [[ -d $ZPLUG_HOME ]]; then
    source $ZPLUG_HOME/init.zsh
fi

zplug 'zplug/zplug', hook-build:'zplug --self-manage'

# Theme
zplug "mafredri/zsh-async", defer:0
zplug "sindresorhus/pure", use:pure.zsh, as:theme

# Plugins
zplug "oz/safe-paste"

zplug 'zsh-users/zsh-autosuggestions'
zplug 'zsh-users/zsh-syntax-highlighting'
zplug 'zsh-users/zsh-history-substring-search'

# Execute
zplug check || zplug install
zplug load

# Bindings for history-substring-search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down

# http://stackoverflow.com/questions/23456873/multi-dot-paths-in-zsh-like-cd/41420448#41420448
function expand-dots() {
    local MATCH
    if [[ $LBUFFER =~ '\.\.\.+' ]]; then
        LBUFFER=$LBUFFER:fs%\.\.\.%../..%
    fi
}

function expand-dots-then-expand-or-complete() {
    zle expand-dots
    zle expand-or-complete
}

function expand-dots-then-accept-line() {
    zle expand-dots
    zle accept-line
}

zle -N expand-dots
zle -N expand-dots-then-expand-or-complete
zle -N expand-dots-then-accept-line
bindkey '^I' expand-dots-then-expand-or-complete
bindkey '^M' expand-dots-then-accept-line
