autoload colors
colors

# zplug
# Bootstrap
if [[ ! -d $ZPLUG_HOME ]]; then
    echo "Installing zplug..."
    if git clone https://github.com/zplug/zplug $ZPLUG_HOME; then
        echo "SUCCESS: Installed zplug into $ZPLUG_HOME"
    else
        echo "$fg[red]ERROR: Failed while installing zplug! $fg[default]"
    fi
fi

if [[ -d $ZPLUG_HOME ]]; then
    source $ZPLUG_HOME/init.zsh
fi

zplug 'zplug/zplug', hook-build:'zplug --self-manage'

# Plugins
zplug 'zsh-users/zsh-autosuggestions'
zplug 'zsh-users/zsh-syntax-highlighting'
zplug 'zsh-users/zsh-history-substring-search'

zplug "oz/safe-paste"

# Theme
zplug "frmendes/geometry"
export PROMPT_GEOMETRY_EXEC_TIME=true

# Execute
zplug check || zplug install
zplug load

# Bindings for history-substring-search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down
