#!/usr/bin/env sh
set -e

force=false
case "$1" in
  -f) force=true;;
esac

git fetch --all 2>/dev/null
git remote prune origin

$force || echo "This is a dry-run.\nPass -f to delete"
for branch in $(git for-each-ref --format='%(refname:short)' refs/heads); do
    # find configured upstream, if any
    remote=$(git config --get branch.$branch.remote) || continue
    # if tracking local branch, skip
    if [ "$remote" = . ]; then continue; fi
    # if the upstream commit resolves, skip
    ucommit=$(git rev-parse "${branch}@{u}" 2>/dev/null) && continue
    # upstream is invalid - remove local branch, or print removal
    $force && git branch -D $branch || echo "$branch"
done
