#!/usr/bin/env bash

echo -en "<span font='22'>$LABEL</span> <span rise='5000'>"

ssid=$(nmcli -t connection show --active | grep ${BLOCK_INSTANCE:-wlp2s0})

if [ $? == 0 ]; then
  echo -n "$(echo "$ssid" | cut -d ":" -f 1)"
elif [ -z $NOT_CONNECTED_COLOR ]; then
  echo -n "Not connected"
else
  echo -n "<span color='$NOT_CONNECTED_COLOR'>Not connected</span>"
fi

echo "</span>"

