#!/usr/bin/env bash

function bar {
  percent=$1
  width=${BAR_WIDTH:-10}
  
  echo -en "<span font='${LABEL_SIZE:-22}'>$LABEL</span> "
  echo -n "<span rise='5000'>"
  
  end=$(($width - 1))
  for i in $(seq 0 $end); do
    segment=$(($i * (100 / $width)))
    if (( percent > segment )); then
      filled+=${BAR_FILL:-━}
    else
      empty+=${BAR_EMPTY:-┉}
    fi
  done
  
  if [ -z $BAR_FILL_COLOR ]; then
    echo -en "$filled"
  else
    echo -en "<span color='$BAR_FILL_COLOR'>$filled</span>"
  fi
  
  if [ -z $BAR_EMPTY_COLOR ]; then
    echo -en "$empty"
  else
    echo -en "<span color='$BAR_EMPTY_COLOR'>$empty</span>"
  fi
  
  echo "</span>"
}

interface=${BLOCK_INSTANCE:-Master}

case $BLOCK_BUTTON in
  1) amixer -q set $interface toggle ;;
  4) amixer -q set $interface 5%- unmute ;;
  5) amixer -q set $interface 5%+ unmute ;;
esac

info=$(amixer get ${interface:-Master})
percent=$(echo $info | grep "Left"  | awk -F "[][]" '/%/ {gsub ("%", ""); print $2 }')

if echo $info | grep "off"; then
  export BAR_FILL_COLOR=$BAR_MUTE_COLOR
  export BAR_EMPTY_COLOR=$BAR_MUTE_COLOR
fi

bar $percent

