#! /usr/bin/env bash

export PLUGIN_DIR="$CONFIG_DIR/plugins"
export ITEMS_DIR="$CONFIG_DIR/items"

FONT="SF Pro"
PADDING=4

source "$CONFIG_DIR"/colors.sh

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

bar=(
  height=45
  color="$BAR_COLOR"
  border_width=2
  border_color="$BAR_BORDER_COLOR"
  shadow=off
  position=top
  sticky=off
  padding_right=10
  padding_left=10
  y_offset=-5
  margin=-2
  color=0x00000000
  border_color=0x00000000
)
sketchybar --bar "${bar[@]}"

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  updates=when_shown
  icon.font="$FONT:Regular:14.0"
  icon.color="$ICON_COLOR"
  icon.padding_left="$PADDIN"
  icon.padding_right="$PADDING"

  label.font="$FONT:Semibold:13.0"
  label.color="$LABEL_COLOR"
  label.padding_left="$PADDING"
  label.padding_right="$PADDING"
  label.shadow.drawing=on
  label.shadow.distance=2
  label.shadow.color=0xff000000

  padding_right="$PADDING"
  padding_left="$PADDING"

  background.height=26
  background.corner_radius=9
  background.border_width=2

  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color="$POPUP_BORDER_COLOR"
  popup.background.color="$POPUP_BACKGROUND_COLOR"
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)
sketchybar --default "${default[@]}"

sketchybar --add event aerospace_workspace_change

items=(
  "spaces"
  "front_app"
  "calendar"
  "battery"
  "volume"
  "cpu"
)

# shellcheck source=/dev/null
for f in "${items[@]}"; do source "$ITEMS_DIR"/"$f".sh; done

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
